# Generated by Django 6.1.1 on 2026-10-04 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import anamnesis.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('scheduling', '0009_appointment_additional_services_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('whatsapp', models.CharField(max_length=30)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('how_met', models.CharField(blank=True, max_length=150)),
                ('had_previous_extension', models.BooleanField()),
                ('had_previous_extension_notes', models.TextField(blank=True, max_length=500)),
                ('has_allergies', models.BooleanField()),
                ('has_allergies_notes', models.TextField(blank=True, max_length=500)),
                ('uses_contact_lenses', models.BooleanField()),
                ('uses_contact_lenses_notes', models.TextField(blank=True, max_length=500)),
                ('has_eye_problems', models.BooleanField()),
                ('has_eye_problems_notes', models.TextField(blank=True, max_length=500)),
                ('recent_eye_procedure', models.BooleanField()),
                ('recent_eye_procedure_notes', models.TextField(blank=True, max_length=500)),
                ('thyroid_alopecia_hormonal', models.BooleanField()),
                ('thyroid_alopecia_hormonal_notes', models.TextField(blank=True, max_length=500)),
                ('pregnant_or_treatment', models.BooleanField()),
                ('pregnant_or_treatment_notes', models.TextField(blank=True, max_length=500)),
                ('pulls_lashes_or_sleeps_prone', models.BooleanField()),
                ('pulls_lashes_or_sleeps_prone_notes', models.TextField(blank=True, max_length=500)),
                ('consent_accepted', models.BooleanField(default=False)),
                ('signed_date', models.DateField()),
                ('signature', models.ImageField(storage=anamnesis.storage.PrivateFileSystemStorage(), upload_to='signatures/%Y/%m/')),
                ('procedure_date', models.DateField(blank=True, null=True)),
                ('technique', models.CharField(blank=True, choices=[('fio_a_fio', 'Fio a Fio'), ('volume_russo', 'Vol. Russo'), ('hibrido', 'Híbrido')], max_length=20)),
                ('curvature', models.CharField(blank=True, max_length=20)),
                ('thickness', models.CharField(blank=True, max_length=20)),
                ('adhesive', models.CharField(blank=True, max_length=100)),
                ('mapping', models.CharField(blank=True, choices=[('gatinho', 'Gatinho'), ('boneca', 'Boneca'), ('esquilo', 'Esquilo')], max_length=20)),
                ('pdf', models.FileField(blank=True, storage=anamnesis.storage.PrivateFileSystemStorage(), upload_to='pdfs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamnesis', to='scheduling.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='professionals.professional')),
            ],
            options={
                'verbose_name': 'ficha de anamnese',
                'verbose_name_plural': 'fichas de anamnese',
                'ordering': ['-created_at'],
            },
        ),
    ]
