# Generated by Django 6.1.1 on 2026-10-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesis',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
