# Generated by Django 6.1.1 on 2026-09-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='lunch_end_time',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='lunch_start_time',
            field=models.TimeField(default='12:00'),
        ),
    ]
