# Generated by Django 6.1.1 on 2026-09-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_workinghours_lunch_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='lunch_end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='lunch_start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
