# Generated by Django 6.1.1 on 2026-09-18 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
        ('scheduling', '0006_alter_workinghours_lunch_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_breaks', to='professionals.professional')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('professional', 'date'), name='unique_lunch_break_per_day')],
            },
        ),
    ]
