# Generated by Django 6.1.1 on 2026-09-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_lunchbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchbreak',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
