# Generated by Django 6.1.1 on 2026-09-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_lunchbreak_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='additional_appointments', to='scheduling.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
